# Generated by Django 5.1.6 on 2025-03-04 17:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_attendance_id_alter_customuser_id_alter_fee_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentimage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
