# Generated by Django 5.1.6 on 2025-04-23 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_studentimage_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.school'),
        ),
    ]
