# Generated by Django 5.1.6 on 2025-11-09 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_topic_unique_together'),
        ('students', '0006_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonplan',
            name='planned_topic_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planned_lessons', to='books.topic'),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='planned_topic',
            field=models.TextField(blank=True, null=True),
        ),
    ]
