# Generated by Django 5.1.6 on 2025-11-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_topic_unique_together'),
        ('students', '0007_lessonplan_planned_topic_fk_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lessonplan',
            unique_together={('session_date', 'teacher', 'student_class', 'school')},
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='planned_topics',
            field=models.ManyToManyField(blank=True, related_name='planned_lessons', to='books.topic'),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.RemoveField(
            model_name='lessonplan',
            name='planned_topic_fk',
        ),
    ]
