# Generated by Django 5.2.8 on 2025-12-12 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_m2m_with_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='date_received',
            field=models.DateField(blank=True, null=True),
        ),
    ]
