# Generated by Django 5.2.8 on 2025-12-27 16:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_alter_school_options_school_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='monthly_subscription_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total monthly subscription (only for monthly_subscription mode)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='school',
            name='payment_mode',
            field=models.CharField(choices=[('per_student', 'Per Student'), ('monthly_subscription', 'Monthly Subscription')], default='per_student', help_text='Payment calculation method for this school', max_length=20),
        ),
    ]
