# Generated by Django 5.2.8 on 2026-01-01 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_customuser_created_at_customuser_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_photo_url',
            field=models.URLField(blank=True, help_text='URL to profile photo in Supabase storage', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(error_messages={'unique': 'A user with this email already exists.'}, max_length=254, null=True, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with this username already exists.'}, max_length=150, unique=True, verbose_name='username'),
        ),
    ]
