# Generated by Django 5.2.8 on 2026-01-02 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_customuser_profile_photo_url_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profile_photo_url',
        ),
        migrations.AddField(
            model_name='student',
            name='profile_photo_url',
            field=models.URLField(blank=True, help_text='URL to profile photo in Supabase storage', max_length=500, null=True),
        ),
    ]
