# Generated by Django 5.2.8 on 2026-01-02 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_remove_customuser_profile_photo_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_photo_url',
            field=models.URLField(blank=True, help_text='URL to profile photo in Supabase storage', max_length=500, null=True),
        ),
    ]
