# Generated by Django 5.2.8 on 2026-01-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_customuser_profile_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Teacher', 'Teacher'), ('Student', 'Student'), ('BDM', 'Business Development Manager')], default='Student', max_length=50),
        ),
    ]
