# Generated by Django 5.2.8 on 2026-01-20 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, help_text='When the school was deactivated', null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, help_text='User who deactivated this school', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schools_deactivated', to=settings.AUTH_USER_MODEL),
        ),
    ]
