# Generated by Django 5.2.8 on 2026-01-20 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0018_fix_email_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('out_of_range', 'Out of Range'), ('location_unavailable', 'Location Unavailable')], default='present', max_length=25)),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('login_latitude', models.DecimalField(blank=True, decimal_places=7, help_text="Teacher's latitude at login time", max_digits=10, null=True)),
                ('login_longitude', models.DecimalField(blank=True, decimal_places=7, help_text="Teacher's longitude at login time", max_digits=10, null=True)),
                ('distance_from_school', models.DecimalField(blank=True, decimal_places=2, help_text='Distance from school in meters', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_attendances', to='students.school')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher Attendance',
                'verbose_name_plural': 'Teacher Attendances',
                'ordering': ['-date', '-login_time'],
                'unique_together': {('teacher', 'school', 'date')},
            },
        ),
    ]
