# Generated by Django 5.2.8 on 2026-01-20 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0019_teacher_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='assigned_days',
            field=models.JSONField(blank=True, default=list, help_text='Days of week when this school has classes. [0=Mon, 1=Tue, 2=Wed, 3=Thu, 4=Fri, 5=Sat, 6=Sun]'),
        ),
    ]
