# Generated by Django 5.2.8 on 2026-01-20 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0020_add_assigned_days_to_school'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teacherattendance',
            unique_together={('teacher', 'date')},
        ),
    ]
