# Generated by Django 5.2.8 on 2026-01-22 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0021_change_teacher_attendance_unique_constraint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='profile_photo_url',
        ),
    ]
