# Generated by Django 5.2.8 on 2026-01-25 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0022_remove_student_profile_photo_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text="Emoji or icon identifier (e.g., '⭐', 'star', 'trophy')", max_length=50)),
                ('badge_type', models.CharField(choices=[('streak_5', '5 Day Streak'), ('streak_10', '10 Day Streak'), ('streak_30', '30 Day Streak'), ('perfect_week', 'Perfect Week'), ('first_month', 'First Month Complete')], max_length=50, unique=True)),
                ('criteria_value', models.IntegerField(help_text='Number required to earn badge (e.g., 5 for 5-day streak)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Badge',
                'verbose_name_plural': 'Badges',
                'ordering': ['criteria_value'],
            },
        ),
        migrations.CreateModel(
            name='StudentBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_badges', to='students.badge')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_badges', to='students.student')),
            ],
            options={
                'verbose_name': 'Student Badge',
                'verbose_name_plural': 'Student Badges',
                'ordering': ['-earned_at'],
                'unique_together': {('student', 'badge')},
            },
        ),
    ]
