# Generated by Django 5.2.8 on 2026-01-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0024_seed_badges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='badge_type',
            field=models.CharField(choices=[('streak_5', '5 Day Streak'), ('streak_10', '10 Day Streak'), ('streak_30', '30 Day Streak'), ('perfect_week', 'Perfect Week'), ('first_month', 'First Month Complete'), ('gala_champion', 'AI Gala Champion'), ('gala_innovator', 'AI Gala Innovator'), ('gala_creator', 'AI Gala Creator'), ('gala_participant', 'Gala Participant'), ('gala_veteran', 'Gala Veteran'), ('gala_superstar', 'Gala Superstar')], max_length=50, unique=True),
        ),
    ]
