# Generated by Django 5.2.8 on 2026-01-29 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0025_add_gallery_targeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherattendance',
            name='location_cleared',
            field=models.BooleanField(default=False, help_text='Whether location data was cleared on logout'),
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='logout_time',
            field=models.DateTimeField(blank=True, help_text='Time when teacher logged out', null=True),
        ),
    ]
