# Generated by Django 5.2.8 on 2026-01-29 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0026_activity_proof_and_logout'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='end_time',
            field=models.TimeField(blank=True, help_text='School end time (e.g., 15:00). If not set, defaults to 3:00 PM', null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='start_time',
            field=models.TimeField(blank=True, help_text='School start time (e.g., 08:00). If not set, defaults to 8:00 AM', null=True),
        ),
    ]
