# Generated by Django 5.1.15 on 2026-05-18 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0026_student_student_subtype'),
        ('students', '0027_guardian_review_and_school_timing'),
    ]

    operations = [
    ]
