# Generated by Django 5.1.15 on 2026-05-20 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_salaryslip_monitoring_snapshot'),
        ('students', '0028_merge_20260518_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Human-readable label, e.g. "Mon/Wed 4-5pm"', max_length=100)),
                ('days', models.CharField(help_text='Comma-separated day codes, e.g. "Mon,Wed" or "Sat"', max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='students.school')),
                ('teacher', models.ForeignKey(blank=True, help_text='Teacher who owns and teaches this slot', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_slots', to='employees.teacherprofile')),
            ],
            options={
                'verbose_name': 'Time Slot',
                'verbose_name_plural': 'Time Slots',
                'ordering': ['school', 'start_time'],
            },
        ),
        migrations.AddField(
            model_name='student',
            name='time_slot',
            field=models.ForeignKey(blank=True, help_text='Scheduling group for ONLINE students (analogous to student_class for ONSITE)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='students.timeslot'),
        ),
    ]
