# Generated by Django 5.1.6 on 2026-07-30 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0029_add_timeslot_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start_date', models.DateField(help_text='Monday of the checked-in week')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_checkins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Weekly Check-In',
                'verbose_name_plural': 'Weekly Check-Ins',
                'ordering': ['-week_start_date'],
                'unique_together': {('user', 'week_start_date')},
            },
        ),
    ]
