# Generated by Django 5.2.8 on 2026-01-15 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(help_text='To: field value', max_length=200)),
                ('subject', models.CharField(help_text='Report subject/title', max_length=200)),
                ('body_text', models.TextField(help_text='Full body content with formatting markers')),
                ('line_spacing', models.CharField(choices=[('single', 'Single'), ('1.5', '1.5'), ('double', 'Double')], default='single', max_length=10)),
                ('template_type', models.CharField(choices=[('custom', 'Custom Report'), ('offer_letter', 'Offer Letter'), ('experience_letter', 'Experience Letter'), ('warning_letter', 'Warning Letter'), ('termination_letter', 'Termination Letter'), ('appreciation_letter', 'Appreciation Letter'), ('salary_certificate', 'Salary Certificate'), ('employment_certificate', 'Employment Certificate'), ('recommendation_letter', 'Recommendation Letter')], default='custom', help_text='Type of report template used', max_length=30)),
                ('generated_by_name', models.CharField(blank=True, help_text='Snapshot of admin name at generation time', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_by', models.ForeignKey(help_text='Admin who generated this report', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_custom_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Custom Report',
                'verbose_name_plural': 'Custom Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
