# Generated by Django 5.2.8 on 2026-01-24 15:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        ('students', '0022_remove_student_profile_photo_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Machine-readable identifier (e.g., salary_certificate)', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Human-readable name', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Template purpose and usage guidelines')),
                ('category', models.CharField(choices=[('hr', 'HR Documents'), ('academic', 'Academic'), ('financial', 'Financial'), ('other', 'Other')], default='other', max_length=50)),
                ('allowed_roles', models.JSONField(default=list, help_text='List of roles that can request: ["Admin", "Teacher", "BDM"]')),
                ('allowed_self_request', models.BooleanField(default=True, help_text='Can users request this for themselves?')),
                ('allowed_other_request', models.BooleanField(default=False, help_text='Can users request this for other employees?')),
                ('requires_target_employee', models.BooleanField(default=True, help_text='Does this template need a target employee?')),
                ('requires_target_school', models.BooleanField(default=False, help_text='Does this template need a target school?')),
                ('default_subject', models.CharField(blank=True, help_text='Default subject line', max_length=200)),
                ('default_body', models.TextField(blank=True, help_text='Default body content with placeholders')),
                ('background_image', models.URLField(blank=True, help_text='Custom background image URL', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Report Template',
                'verbose_name_plural': 'Report Templates',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='customreport',
            name='recipient',
            field=models.TextField(help_text='To: field value (supports multiline)'),
        ),
        migrations.CreateModel(
            name='ReportRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_number', models.CharField(blank=True, help_text='Auto-generated: REQ-YYYY-NNNN', max_length=20, unique=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.CharField(max_length=200)),
                ('recipient_text', models.TextField(blank=True, help_text='Formatted recipient (To: field)')),
                ('body_text', models.TextField(help_text='Editable body content (DRAFT only)')),
                ('content_snapshot', models.JSONField(blank=True, help_text='Frozen content after submission - immutable', null=True)),
                ('line_spacing', models.CharField(choices=[('single', 'Single'), ('1.5', '1.5'), ('double', 'Double')], default='single', max_length=10)),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='Template-specific custom data')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('GENERATED', 'Generated'), ('CANCELLED', 'Cancelled'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Why request was rejected')),
                ('admin_notes', models.TextField(blank=True, help_text='Internal admin notes')),
                ('expires_at', models.DateTimeField(blank=True, help_text='When request expires', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Admin who approved', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_report_requests', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(help_text='User who created the request', on_delete=django.db.models.deletion.CASCADE, related_name='report_requests', to=settings.AUTH_USER_MODEL)),
                ('target_employee', models.ForeignKey(blank=True, help_text='Employee the report is about (null = self)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_about_me', to=settings.AUTH_USER_MODEL)),
                ('target_school', models.ForeignKey(blank=True, help_text='For school-specific reports', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_requests', to='students.school')),
                ('template', models.ForeignKey(help_text='Selected report template', on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='reports.reporttemplate')),
            ],
            options={
                'verbose_name': 'Report Request',
                'verbose_name_plural': 'Report Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('file_path', models.CharField(help_text='Storage path (Supabase or local)', max_length=500)),
                ('file_name', models.CharField(max_length=200)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('file_hash', models.CharField(help_text='SHA256 hash for integrity verification', max_length=64)),
                ('mime_type', models.CharField(default='application/pdf', max_length=50)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('last_downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
                ('last_downloaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downloaded_reports', to=settings.AUTH_USER_MODEL)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='generated_report', to='reports.reportrequest')),
            ],
            options={
                'verbose_name': 'Generated Report',
                'verbose_name_plural': 'Generated Reports',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_status_changes', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='reports.reportrequest')),
            ],
            options={
                'verbose_name': 'Request Status Log',
                'verbose_name_plural': 'Request Status Logs',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='reportrequest',
            index=models.Index(fields=['status'], name='reports_rep_status_c8cc48_idx'),
        ),
        migrations.AddIndex(
            model_name='reportrequest',
            index=models.Index(fields=['requested_by'], name='reports_rep_request_5ba7f9_idx'),
        ),
        migrations.AddIndex(
            model_name='reportrequest',
            index=models.Index(fields=['created_at'], name='reports_rep_created_b07b87_idx'),
        ),
        migrations.AddIndex(
            model_name='reportrequest',
            index=models.Index(fields=['template'], name='reports_rep_templat_8812ed_idx'),
        ),
        migrations.AddIndex(
            model_name='requeststatuslog',
            index=models.Index(fields=['request'], name='reports_req_request_6f6314_idx'),
        ),
        migrations.AddIndex(
            model_name='requeststatuslog',
            index=models.Index(fields=['changed_at'], name='reports_req_changed_d3631a_idx'),
        ),
    ]
