# Generated by Django 5.1.15 on 2026-04-29 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_self_service_reports'),
        ('students', '0027_guardian_review_and_school_timing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentReportGenerationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('single_pdf', 'Single PDF'), ('bulk_pdf_item', 'Bulk PDF Item')], max_length=20)),
                ('student_class', models.CharField(blank=True, max_length=50)),
                ('period_mode', models.CharField(choices=[('month', 'Month'), ('range', 'Date Range')], max_length=10)),
                ('period_month', models.CharField(blank=True, help_text='YYYY-MM for month mode', max_length=7, null=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('request_id', models.UUIDField(blank=True, help_text='Groups events from one bulk request', null=True)),
                ('source', models.CharField(choices=[('reports_page', 'Reports Page')], default='reports_page', max_length=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_report_generation_events', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_generation_events', to='students.school')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_generation_events', to='students.student')),
            ],
            options={
                'verbose_name': 'Student Report Generation Event',
                'verbose_name_plural': 'Student Report Generation Events',
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['generated_at'], name='reports_stu_generat_6667b8_idx'), models.Index(fields=['period_month'], name='reports_stu_period__1d8e3d_idx'), models.Index(fields=['generated_by', 'generated_at'], name='reports_stu_generat_0ef1eb_idx'), models.Index(fields=['school', 'student_class', 'period_month'], name='reports_stu_school__bb7441_idx'), models.Index(fields=['request_id'], name='reports_stu_request_4cd995_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('request_id__isnull', False)), fields=('request_id', 'student', 'event_type'), name='uniq_bulk_request_student_event_type')],
            },
        ),
    ]
