# Generated by Django 5.1.6 on 2026-07-30 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_studentreportgenerationevent'),
        ('students', '0030_weeklycheckin'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyNarrative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(help_text='YYYY-MM', max_length=7)),
                ('narrative', models.TextField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.CharField(blank=True, help_text='Which LLM provider generated this (ollama/groq)', max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_narratives', to='students.student')),
            ],
            options={
                'verbose_name': 'Monthly Narrative',
                'verbose_name_plural': 'Monthly Narratives',
                'ordering': ['-month'],
                'unique_together': {('student', 'month')},
            },
        ),
    ]
