INSERT INTO auth_permission (name, content_type, codename) VALUES ('Can add log entry', '1', 'add_logentry');
INSERT INTO auth_permission (name, content_type, codename) VALUES ('Can change log entry', '1', 'change_logentry');
INSERT INTO auth_permission (name, content_type, codename) VALUES ('Can delete log entry', '1', 'delete_logentry');
INSERT INTO auth_permission (name, content_type, codename) VALUES ('Can view log entry', '1', 'view_logentry');
INSERT INTO auth_permission (name, content_type, codename) VALUES ('Can add permission', '2', 'add_permission');
INSERT INTO auth_permission (name, content_type, codename) VALUES ('Can change permission', '2', 'change_permission');
INSERT INTO auth_permission (name, content_type, codename) VALUES ('Can delete permission', '2', 'delete_permission');
INSERT INTO auth_permission (name, content_type, codename) VALUES ('Can view permission', '2', 'view_permission');
INSERT INTO auth_permission (name, content_type, codename) VALUES ('Can add group', '3', 'add_group');
INSERT INTO auth_permission (name, content_type, codename) VALUES ('Can change group', '3', 'change_group');
INSERT INTO auth_permission (name, content_type, codename) VALUES ('Can delete group', '3', 'delete_group');
INSERT INTO auth_permission (name, content_type, codename) VALUES ('Can view group', '3', 'view_group');
INSERT INTO auth_permission (name, content_type, codename) VALUES ('Can add content type', '4', 'add_contenttype');
INSERT INTO auth_permission (name, content_type, codename) VALUES ('Can change content type', '4', 'change_contenttype');
INSERT INTO auth_permission (name, content_type, codename) VALUES ('Can delete content type', '4', 'delete_contenttype');
INSERT INTO auth_permission (name, content_type, codename) VALUES ('Can view content type', '4', 'view_contenttype');
INSERT INTO auth_permission (name, content_type, codename) VALUES ('Can add session', '5', 'add_session');
INSERT INTO auth_permission (name, content_type, codename) VALUES ('Can change session', '5', 'change_session');
INSERT INTO auth_permission (name, content_type, codename) VALUES ('Can delete session', '5', 'delete_session');
INSERT INTO auth_permission (name, content_type, codename) VALUES ('Can view session', '5', 'view_session');
INSERT INTO auth_permission (name, content_type, codename) VALUES ('Can add user', '6', 'add_customuser');
INSERT INTO auth_permission (name, content_type, codename) VALUES ('Can change user', '6', 'change_customuser');
INSERT INTO auth_permission (name, content_type, codename) VALUES ('Can delete user', '6', 'delete_customuser');
INSERT INTO auth_permission (name, content_type, codename) VALUES ('Can view user', '6', 'view_customuser');
INSERT INTO auth_permission (name, content_type, codename) VALUES ('Can add Student', '7', 'add_student');
INSERT INTO auth_permission (name, content_type, codename) VALUES ('Can change Student', '7', 'change_student');
INSERT INTO auth_permission (name, content_type, codename) VALUES ('Can delete Student', '7', 'delete_student');
INSERT INTO auth_permission (name, content_type, codename) VALUES ('Can view Student', '7', 'view_student');
INSERT INTO auth_permission (name, content_type, codename) VALUES ('Can add school', '8', 'add_school');
INSERT INTO auth_permission (name, content_type, codename) VALUES ('Can change school', '8', 'change_school');
INSERT INTO auth_permission (name, content_type, codename) VALUES ('Can delete school', '8', 'delete_school');
INSERT INTO auth_permission (name, content_type, codename) VALUES ('Can view school', '8', 'view_school');
INSERT INTO auth_permission (name, content_type, codename) VALUES ('Can add fee', '9', 'add_fee');
INSERT INTO auth_permission (name, content_type, codename) VALUES ('Can change fee', '9', 'change_fee');
INSERT INTO auth_permission (name, content_type, codename) VALUES ('Can delete fee', '9', 'delete_fee');
INSERT INTO auth_permission (name, content_type, codename) VALUES ('Can view fee', '9', 'view_fee');
INSERT INTO auth_permission (name, content_type, codename) VALUES ('Can add blacklisted token', '10', 'add_blacklistedtoken');
INSERT INTO auth_permission (name, content_type, codename) VALUES ('Can change blacklisted token', '10', 'change_blacklistedtoken');
INSERT INTO auth_permission (name, content_type, codename) VALUES ('Can delete blacklisted token', '10', 'delete_blacklistedtoken');
INSERT INTO auth_permission (name, content_type, codename) VALUES ('Can view blacklisted token', '10', 'view_blacklistedtoken');
INSERT INTO auth_permission (name, content_type, codename) VALUES ('Can add outstanding token', '11', 'add_outstandingtoken');
INSERT INTO auth_permission (name, content_type, codename) VALUES ('Can change outstanding token', '11', 'change_outstandingtoken');
INSERT INTO auth_permission (name, content_type, codename) VALUES ('Can delete outstanding token', '11', 'delete_outstandingtoken');
INSERT INTO auth_permission (name, content_type, codename) VALUES ('Can view outstanding token', '11', 'view_outstandingtoken');
INSERT INTO auth_permission (name, content_type, codename) VALUES ('Can add attendance', '12', 'add_attendance');
INSERT INTO auth_permission (name, content_type, codename) VALUES ('Can change attendance', '12', 'change_attendance');
INSERT INTO auth_permission (name, content_type, codename) VALUES ('Can delete attendance', '12', 'delete_attendance');
INSERT INTO auth_permission (name, content_type, codename) VALUES ('Can view attendance', '12', 'view_attendance');
INSERT INTO auth_permission (name, content_type, codename) VALUES ('Can add lesson plan', '13', 'add_lessonplan');
INSERT INTO auth_permission (name, content_type, codename) VALUES ('Can change lesson plan', '13', 'change_lessonplan');
INSERT INTO auth_permission (name, content_type, codename) VALUES ('Can delete lesson plan', '13', 'delete_lessonplan');
INSERT INTO auth_permission (name, content_type, codename) VALUES ('Can view lesson plan', '13', 'view_lessonplan');
INSERT INTO auth_permission (name, content_type, codename) VALUES ('Can add student image', '14', 'add_studentimage');
INSERT INTO auth_permission (name, content_type, codename) VALUES ('Can change student image', '14', 'change_studentimage');
INSERT INTO auth_permission (name, content_type, codename) VALUES ('Can delete student image', '14', 'delete_studentimage');
INSERT INTO auth_permission (name, content_type, codename) VALUES ('Can view student image', '14', 'view_studentimage');
INSERT INTO auth_permission (name, content_type, codename) VALUES ('Can add transaction', '15', 'add_transaction');
INSERT INTO auth_permission (name, content_type, codename) VALUES ('Can change transaction', '15', 'change_transaction');
INSERT INTO auth_permission (name, content_type, codename) VALUES ('Can delete transaction', '15', 'delete_transaction');
INSERT INTO auth_permission (name, content_type, codename) VALUES ('Can view transaction', '15', 'view_transaction');
INSERT INTO auth_permission (name, content_type, codename) VALUES ('Can add account', '16', 'add_account');
INSERT INTO auth_permission (name, content_type, codename) VALUES ('Can change account', '16', 'change_account');
INSERT INTO auth_permission (name, content_type, codename) VALUES ('Can delete account', '16', 'delete_account');
INSERT INTO auth_permission (name, content_type, codename) VALUES ('Can view account', '16', 'view_account');
