web: gunicorn school_management.wsgi:application --bind 0.0.0.0:$PORT
worker: celery -A school_management worker --loglevel=info
beat: celery -A school_management beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler