# Generated by Django 5.2.8 on 2026-01-27 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aigala', '0002_seed_gala_badges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='class_date',
            field=models.DateField(blank=True, help_text='When the AI Gala class happens', null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='gallery_open_date',
            field=models.DateField(blank=True, help_text='When gallery becomes visible', null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='voting_end_date',
            field=models.DateField(blank=True, help_text='When voting closes', null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='voting_start_date',
            field=models.DateField(blank=True, help_text='When voting begins', null=True),
        ),
    ]
