# Generated by Django 5.2.8 on 2026-01-27 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aigala', '0003_make_gallery_dates_optional'),
        ('students', '0025_add_gallery_targeting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_galleries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gallery',
            name='target_classes',
            field=models.JSONField(blank=True, default=list, help_text="Class names that can participate (e.g., ['Level 1', 'Level 2']). Empty = all classes."),
        ),
        migrations.AddField(
            model_name='gallery',
            name='target_schools',
            field=models.ManyToManyField(blank=True, help_text='Schools that can participate. Empty = all schools.', related_name='gala_galleries', to='students.school'),
        ),
    ]
