# Generated by Django 5.2.8 on 2026-01-03 17:25

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0016_alter_customuser_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(blank=True, help_text='Name of the prospective school', max_length=200, null=True)),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=20, null=True)),
                ('contact_person', models.CharField(blank=True, help_text='Name of contact person', max_length=100, null=True)),
                ('email', models.EmailField(blank=True, help_text='Contact email', max_length=254, null=True)),
                ('address', models.TextField(blank=True, help_text='Physical address', null=True)),
                ('city', models.CharField(blank=True, help_text='City', max_length=100, null=True)),
                ('lead_source', models.CharField(choices=[('Website', 'Website'), ('Referral', 'Referral'), ('Cold Call', 'Cold Call'), ('Walk-in', 'Walk-in'), ('Social Media', 'Social Media'), ('Other', 'Other')], default='Other', help_text='How did this lead come to us?', max_length=50)),
                ('status', models.CharField(choices=[('New', 'New'), ('Contacted', 'Contacted'), ('Interested', 'Interested'), ('Not Interested', 'Not Interested'), ('Converted', 'Converted'), ('Lost', 'Lost')], default='New', help_text='Current status of the lead', max_length=20)),
                ('conversion_date', models.DateTimeField(blank=True, help_text='Date when lead was converted to school', null=True)),
                ('estimated_students', models.IntegerField(blank=True, help_text='Estimated number of students', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this lead', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='BDM responsible for this lead', limit_choices_to={'role': 'BDM'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
                ('converted_to_school', models.ForeignKey(blank=True, help_text='School created from this lead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_lead', to='students.school')),
                ('created_by', models.ForeignKey(help_text='User who created this lead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('Call', 'Phone Call'), ('Meeting', 'Meeting')], help_text='Type of activity', max_length=20)),
                ('subject', models.CharField(help_text='Brief subject of the activity', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the activity', null=True)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Scheduled', help_text='Current status of the activity', max_length=20)),
                ('scheduled_date', models.DateTimeField(help_text='When this activity is scheduled')),
                ('completed_date', models.DateTimeField(blank=True, help_text='When this activity was completed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(help_text='User responsible for this activity', on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(help_text='Lead this activity is related to', on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.lead')),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='BDMTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Yearly', 'Yearly')], default='Monthly', help_text='Type of target period', max_length=20)),
                ('start_date', models.DateField(help_text='Start date of target period')),
                ('end_date', models.DateField(help_text='End date of target period')),
                ('leads_target', models.IntegerField(default=0, help_text='Target number of new leads', validators=[django.core.validators.MinValueValidator(0)])),
                ('conversions_target', models.IntegerField(default=0, help_text='Target number of converted schools', validators=[django.core.validators.MinValueValidator(0)])),
                ('revenue_target', models.DecimalField(decimal_places=2, default=0.0, help_text='Expected revenue target', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('leads_achieved', models.IntegerField(default=0, editable=False, help_text='Actual leads created (auto-calculated)')),
                ('conversions_achieved', models.IntegerField(default=0, editable=False, help_text='Actual conversions (auto-calculated)')),
                ('revenue_achieved', models.DecimalField(decimal_places=2, default=0.0, editable=False, help_text='Actual revenue achieved (auto-calculated)', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bdm', models.ForeignKey(help_text='BDM user for this target', limit_choices_to={'role': 'BDM'}, on_delete=django.db.models.deletion.CASCADE, related_name='targets', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(help_text='Admin who created this target', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BDM Target',
                'verbose_name_plural': 'BDM Targets',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['bdm'], name='crm_bdmtarg_bdm_id_1fc5d9_idx'), models.Index(fields=['start_date', 'end_date'], name='crm_bdmtarg_start_d_6a4f41_idx')],
                'unique_together': {('bdm', 'start_date', 'end_date')},
            },
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status'], name='crm_lead_status_2c1bc7_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['assigned_to'], name='crm_lead_assigne_2d9eb1_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['created_at'], name='crm_lead_created_d9bbc3_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['lead'], name='crm_activit_lead_id_bf4686_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['assigned_to'], name='crm_activit_assigne_522fa8_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['scheduled_date'], name='crm_activit_schedul_d62727_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['status'], name='crm_activit_status_2d8c1f_idx'),
        ),
    ]
