# Generated by Django 5.2.8 on 2026-02-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Duration of call/meeting in minutes', null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='is_logged',
            field=models.BooleanField(default=False, help_text='True if activity was logged after completion (not scheduled in advance)'),
        ),
        migrations.AddField(
            model_name='activity',
            name='outcome',
            field=models.CharField(blank=True, choices=[('Interested', 'Interested'), ('Not Interested', 'Not Interested'), ('Follow-up Required', 'Follow-up Required'), ('No Answer', 'No Answer'), ('Wrong Number', 'Wrong Number'), ('Callback Requested', 'Callback Requested'), ('Other', 'Other')], help_text='Outcome of the activity', max_length=30, null=True),
        ),
    ]
