# Generated by Django 5.2.11 on 2026-02-27 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_activity_duration_minutes_activity_is_logged_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('standard_rate', models.CharField(default='PKR 2,500', max_length=50)),
                ('discounted_rate', models.CharField(default='PKR 1,000', max_length=50)),
                ('generated_by_name', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_proposals', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='crm.lead')),
            ],
            options={
                'verbose_name': 'Proposal Offer',
                'verbose_name_plural': 'Proposal Offers',
                'ordering': ['-created_at'],
            },
        ),
    ]
