# Generated by Django 6.0.2 on 2026-02-27 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_proposaloffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposaloffer',
            name='feature_items',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='proposaloffer',
            name='page_selection',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
