# Generated by Django 5.1.6 on 2026-07-30 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_lead_source_whatsapp_bot'),
        ('students', '0030_weeklycheckin'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='referred_by',
            field=models.ForeignKey(blank=True, help_text='Enrolled student whose parent referred this lead, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_leads', to='students.student'),
        ),
    ]
