# Generated by Django 5.1.6 on 2025-03-25 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_remove_journalentry_created_by_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TransactionCategory',
        ),
    ]
