# Generated by Django 5.1.6 on 2025-03-24 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_remove_journalentry_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactioncategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Category Name'),
        ),
    ]
