# Generated by Django 5.1.6 on 2025-05-06 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_categoryentry'),
        ('students', '0005_alter_fee_school'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_type'], name='finance_tra_transac_2a23c2_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['category'], name='finance_tra_categor_afb10f_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['school'], name='finance_tra_school__92c62a_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['from_account'], name='finance_tra_from_ac_a3e926_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['to_account'], name='finance_tra_to_acco_ab42e9_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['date'], name='finance_tra_date_f21d66_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_type', 'category'], name='finance_tra_transac_3ea21d_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['school', 'date'], name='finance_tra_school__77cea9_idx'),
        ),
    ]
