# Generated by Django 5.1.6 on 2025-10-14 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('students', '0005_alter_fee_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='location',
            field=models.CharField(choices=[('School', 'School'), ('Headquarters', 'Headquarters'), ('Unassigned', 'Unassigned')], default='School', max_length=20),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.school'),
        ),
    ]
