# Generated by Django 5.1.15 on 2026-08-27 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_inventoryitem_purchase_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='location',
            field=models.CharField(choices=[('School', 'School'), ('Headquarters', 'Headquarters'), ('Unassigned', 'Unassigned')], db_index=True, default='School', max_length=20),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Assigned', 'Assigned'), ('Damaged', 'Damaged'), ('Lost', 'Lost'), ('Disposed', 'Disposed')], db_index=True, default='Available', max_length=20),
        ),
    ]
