# Generated by Django 6.0.1 on 2026-02-12 19:06

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0027_guardian_review_and_school_timing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationFormTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_form_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evaluation Form Template',
                'verbose_name_plural': 'Evaluation Form Templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationFormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('field_type', models.CharField(choices=[('rating_1_5', 'Rating 1-5'), ('rating_1_10', 'Rating 1-10'), ('text', 'Text Input'), ('textarea', 'Text Area'), ('yes_no', 'Yes / No'), ('select', 'Dropdown Select')], max_length=20)),
                ('is_required', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('options', models.JSONField(blank=True, default=list, help_text='Options for select type, e.g. ["Good", "Average", "Poor"]')),
                ('weight', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Weight for score calculation (0 = not scored)', max_digits=5)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='monitoring.evaluationformtemplate')),
            ],
            options={
                'verbose_name': 'Evaluation Form Field',
                'verbose_name_plural': 'Evaluation Form Fields',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MonitoringVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('missed', 'Missed')], default='planned', max_length=20)),
                ('purpose', models.CharField(blank=True, help_text='e.g. Monthly Review, New Teacher Onboarding', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bdm', models.ForeignKey(limit_choices_to={'role': 'BDM'}, on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_visits', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_visits', to='students.school')),
            ],
            options={
                'verbose_name': 'Monitoring Visit',
                'verbose_name_plural': 'Monitoring Visits',
                'ordering': ['-visit_date', '-created_at'],
                'unique_together': {('bdm', 'school', 'visit_date')},
            },
        ),
        migrations.CreateModel(
            name='TeacherEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('normalized_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Score normalized to 0-100 scale', max_digits=5)),
                ('remarks', models.TextField(blank=True)),
                ('areas_of_improvement', models.TextField(blank=True)),
                ('teacher_strengths', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'Teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_evaluations', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to='monitoring.evaluationformtemplate')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='monitoring.monitoringvisit')),
            ],
            options={
                'verbose_name': 'Teacher Evaluation',
                'verbose_name_plural': 'Teacher Evaluations',
                'ordering': ['-submitted_at'],
                'unique_together': {('visit', 'teacher')},
            },
        ),
        migrations.CreateModel(
            name='EvaluationResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(help_text='Stored as text for all field types')),
                ('numeric_value', models.DecimalField(blank=True, decimal_places=2, help_text='Numeric value for rating fields (for scoring)', max_digits=5, null=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='monitoring.evaluationformfield')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='monitoring.teacherevaluation')),
            ],
            options={
                'verbose_name': 'Evaluation Response',
                'verbose_name_plural': 'Evaluation Responses',
                'unique_together': {('evaluation', 'field')},
            },
        ),
    ]
