# Generated by Django 5.2.11 on 2026-02-16 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_seed_default_template'),
        ('students', '0027_guardian_review_and_school_timing'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='monitoringvisit',
            unique_together={('school', 'visit_date')},
        ),
    ]
