# Generated by Django 5.2.11 on 2026-02-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_alter_monitoringvisit_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringvisit',
            name='planned_time',
            field=models.TimeField(blank=True, help_text='BDM planned visit time', null=True),
        ),
    ]
