# Generated by Django 5.2.11 on 2026-02-17 08:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_monitoringvisit_planned_time'),
        ('students', '0027_guardian_review_and_school_timing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='monitoringvisit',
            unique_together={('bdm', 'school', 'visit_date')},
        ),
    ]
