# Generated by Django 5.1.15 on 2026-08-27 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0008_redesign_instant_start_and_freeform_qa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoringvisit',
            name='bdm',
            field=models.ForeignKey(limit_choices_to={'role__in': ['Admin', 'BDM']}, on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_visits', to=settings.AUTH_USER_MODEL),
        ),
    ]
