# Generated by Django 5.2.8 on 2026-01-29 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_add_visibility_and_assignments'),
        ('courses', '0001_lms_initial'),
        ('students', '0026_activity_proof_and_logout'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityProofBulkAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('approve', 'Bulk Approve'), ('reject', 'Bulk Reject')], max_length=20)),
                ('proof_ids', models.JSONField(help_text='List of ActivityProof IDs affected')),
                ('count', models.PositiveIntegerField(help_text='Number of proofs affected')),
                ('rating', models.CharField(blank=True, choices=[('basic', 'Basic'), ('good', 'Good'), ('excellent', 'Excellent')], help_text='Rating applied (for bulk approve)', max_length=20, null=True)),
                ('remarks', models.TextField(blank=True, help_text='Remarks applied to all proofs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_proof_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bulk Action Log',
                'verbose_name_plural': 'Bulk Action Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screenshot_url', models.URLField(help_text='Supabase storage URL for the screenshot', max_length=500)),
                ('software_used', models.CharField(choices=[('scratch', 'Scratch'), ('python', 'Python'), ('canva', 'Canva'), ('ai_tool', 'AI Tool'), ('other', 'Other')], default='other', max_length=20)),
                ('student_notes', models.TextField(blank=True, help_text='Optional notes from student about their activity')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('teacher_remarks', models.TextField(blank=True, help_text="Teacher's feedback on the activity")),
                ('teacher_rating', models.CharField(blank=True, choices=[('basic', 'Basic'), ('good', 'Good'), ('excellent', 'Excellent')], help_text='Quality rating given by teacher', max_length=20, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_proofs', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_proofs', to='courses.courseenrollment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_proofs', to='students.student')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_proofs', to='books.topic')),
            ],
            options={
                'verbose_name': 'Activity Proof',
                'verbose_name_plural': 'Activity Proofs',
                'ordering': ['-uploaded_at'],
                'unique_together': {('student', 'topic')},
            },
        ),
    ]
