# Generated by Django 5.2.8 on 2026-01-29 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_add_visibility_and_assignments'),
        ('courses', '0002_activity_proof_and_logout'),
        ('students', '0027_guardian_review_and_school_timing'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuardianReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=True, help_text='Guardian approval status')),
                ('reviewer_ip', models.GenericIPAddressField(blank=True, help_text='IP address for audit purposes', null=True)),
                ('review_notes', models.TextField(blank=True, help_text='Optional notes from guardian')),
                ('activity_proof', models.OneToOneField(help_text='The approved activity proof being reviewed', on_delete=django.db.models.deletion.CASCADE, related_name='guardian_review', to='courses.activityproof')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_reviews', to='students.student')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_reviews', to='books.topic')),
            ],
            options={
                'verbose_name': 'Guardian Review',
                'verbose_name_plural': 'Guardian Reviews',
                'ordering': ['-reviewed_at'],
                'unique_together': {('student', 'topic')},
            },
        ),
    ]
