# Generated by Django 5.2.8 on 2026-01-29 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_add_visibility_and_assignments'),
        ('courses', '0003_guardian_review_and_school_timing'),
        ('students', '0027_guardian_review_and_school_timing'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_score', models.IntegerField(default=0, help_text='Score based on time spent reading (0-100)')),
                ('activity_score', models.IntegerField(default=0, help_text='Score based on activity completion (0-100)')),
                ('teacher_rating_score', models.IntegerField(default=0, help_text="Score based on teacher's quality rating (0-100)")),
                ('guardian_review_score', models.IntegerField(default=0, help_text='Score based on guardian review (0 or 100)')),
                ('total_score', models.DecimalField(decimal_places=2, default=0, help_text='Weighted total score', max_digits=5)),
                ('rating', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('average', 'Average'), ('needs_support', 'Needs Support')], default='needs_support', max_length=20)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_scores', to='courses.courseenrollment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_scores', to='students.student')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_scores', to='books.topic')),
            ],
            options={
                'verbose_name': 'Section Score',
                'verbose_name_plural': 'Section Scores',
                'ordering': ['-calculated_at'],
                'unique_together': {('student', 'topic')},
            },
        ),
    ]
