# Generated by Django 5.2.8 on 2026-01-19 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.CharField(choices=[('fee', 'Fee Agent'), ('inventory', 'Inventory Agent'), ('hr', 'HR Agent'), ('broadcast', 'Broadcast Agent')], max_length=50)),
                ('user_message', models.TextField(help_text='Original user input')),
                ('context_data', models.JSONField(default=dict, help_text='Context passed to LLM (schools, categories, etc.)')),
                ('llm_raw_response', models.TextField(blank=True, help_text='Raw text response from LLM', null=True)),
                ('llm_parsed_response', models.JSONField(default=dict, help_text='Parsed JSON from LLM', null=True)),
                ('action_name', models.CharField(blank=True, help_text='Action that was executed', max_length=100, null=True)),
                ('action_params', models.JSONField(default=dict, help_text='Parameters passed to action', null=True)),
                ('execution_result', models.JSONField(default=dict, help_text='Result from action execution', null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('clarify', 'Clarification Needed'), ('unsupported', 'Unsupported Request'), ('pending_confirmation', 'Pending Confirmation'), ('confirmed', 'Confirmed & Executed'), ('cancelled', 'Cancelled by User')], default='success', max_length=30)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('confirmation_token', models.CharField(blank=True, help_text='Token for confirming destructive actions', max_length=64, null=True, unique=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('llm_response_time_ms', models.IntegerField(default=0, help_text='LLM response time in milliseconds')),
                ('total_time_ms', models.IntegerField(default=0, help_text='Total request time in milliseconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Audit Log',
                'verbose_name_plural': 'AI Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='ai_aiauditl_user_id_d06d5a_idx'), models.Index(fields=['agent', 'created_at'], name='ai_aiauditl_agent_18bc60_idx'), models.Index(fields=['status', 'created_at'], name='ai_aiauditl_status_60c3ec_idx'), models.Index(fields=['confirmation_token'], name='ai_aiauditl_confirm_621654_idx')],
            },
        ),
    ]
