# Generated by Django 5.2.8 on 2026-01-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiauditlog',
            name='agent',
            field=models.CharField(choices=[('fee', 'Fee Agent'), ('inventory', 'Inventory Agent'), ('hr', 'HR Agent'), ('broadcast', 'Broadcast Agent'), ('task', 'Task Agent')], max_length=50),
        ),
    ]
