from django.db import models
from django.conf import settings


class CustomReport(models.Model):
    """
    Stores custom PDF reports generated by admins.
    """
    TEMPLATE_CHOICES = [
        ('custom', 'Custom Report'),
        ('offer_letter', 'Offer Letter'),
        ('experience_letter', 'Experience Letter'),
        ('warning_letter', 'Warning Letter'),
        ('termination_letter', 'Termination Letter'),
        ('appreciation_letter', 'Appreciation Letter'),
        ('salary_certificate', 'Salary Certificate'),
        ('employment_certificate', 'Employment Certificate'),
        ('recommendation_letter', 'Recommendation Letter'),
    ]

    LINE_SPACING_CHOICES = [
        ('single', 'Single'),
        ('1.5', '1.5'),
        ('double', 'Double'),
    ]

    recipient = models.TextField(help_text="To: field value (supports multiline)")
    subject = models.CharField(max_length=200, help_text="Report subject/title")
    body_text = models.TextField(help_text="Full body content with formatting markers")
    line_spacing = models.CharField(max_length=10, choices=LINE_SPACING_CHOICES, default='single')
    template_type = models.CharField(
        max_length=30,
        choices=TEMPLATE_CHOICES,
        default='custom',
        help_text="Type of report template used"
    )
    generated_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        related_name='generated_custom_reports',
        help_text="Admin who generated this report"
    )
    generated_by_name = models.CharField(
        max_length=200,
        blank=True,
        help_text="Snapshot of admin name at generation time"
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Custom Report"
        verbose_name_plural = "Custom Reports"
        ordering = ['-created_at']

    def __str__(self):
        return f"{self.subject} - {self.recipient} ({self.created_at.strftime('%Y-%m-%d')})"

    @property
    def template_display(self):
        """Return human-readable template type."""
        return dict(self.TEMPLATE_CHOICES).get(self.template_type, self.template_type)

    @property
    def short_body(self):
        """Return truncated body for list views."""
        if len(self.body_text) > 100:
            return self.body_text[:100] + "..."
        return self.body_text
