# Generated by Django 5.1.6 on 2025-11-07 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='type',
            field=models.CharField(choices=[('chapter', 'Chapter'), ('lesson', 'Lesson'), ('activity', 'Activity')], default='lesson', max_length=20),
        ),
    ]
