# Generated by Django 5.1.6 on 2025-11-07 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_topic_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together={('book', 'code', 'type')},
        ),
    ]
