# Generated by Django 5.2.8 on 2026-01-25 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_topic_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='estimated_time_minutes',
            field=models.PositiveIntegerField(default=10, help_text='Estimated time to complete this topic'),
        ),
        migrations.AddField(
            model_name='topic',
            name='is_required',
            field=models.BooleanField(default=True, help_text='Whether topic must be completed for course completion'),
        ),
        migrations.AddField(
            model_name='topic',
            name='video_duration_seconds',
            field=models.PositiveIntegerField(blank=True, help_text='Video duration for progress tracking', null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube/Vimeo embed URL for video content', null=True),
        ),
    ]
