# Generated by Django 5.2.8 on 2026-01-25 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_lms_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, help_text='Course description shown to students before enrollment'),
        ),
        migrations.AddField(
            model_name='book',
            name='difficulty_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='book',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Only published courses are visible to students'),
        ),
        migrations.AddField(
            model_name='topic',
            name='content',
            field=models.TextField(blank=True, help_text='Main content for the topic (intro, explanations). Supports HTML.'),
        ),
        migrations.AddField(
            model_name='topic',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Topic thumbnail or banner image', null=True, upload_to='books/topics/'),
        ),
    ]
