# Generated by Django 5.2.8 on 2026-01-28 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_add_lms_fields'),
        ('students', '0025_add_gallery_targeting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookClassVisibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_class', models.CharField(help_text="Class that can see this book (e.g., 'Class 1', 'PlayGroup')", max_length=50)),
                ('is_visible', models.BooleanField(default=True, help_text='Whether this book is visible to this class')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_visibility', to='books.book')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_visibility_rules', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_visibility', to='students.school')),
            ],
            options={
                'verbose_name': 'Book Class Visibility',
                'verbose_name_plural': 'Book Class Visibility Rules',
                'unique_together': {('book', 'school', 'student_class')},
            },
        ),
        migrations.CreateModel(
            name='TopicAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_class', models.CharField(help_text='Class this assignment applies to', max_length=50)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField(blank=True, help_text='Optional deadline for completing this topic', null=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes/instructions for students')),
                ('is_mandatory', models.BooleanField(default=True, help_text='Whether this assignment is mandatory')),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_topics', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_assignments', to='students.school')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='books.topic')),
            ],
            options={
                'verbose_name': 'Topic Assignment',
                'verbose_name_plural': 'Topic Assignments',
                'ordering': ['-assigned_at'],
                'unique_together': {('topic', 'school', 'student_class')},
            },
        ),
    ]
