# Generated by Django 5.2.8 on 2026-01-19 05:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0016_alter_customuser_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Display name, e.g., 'Check Stock'", max_length=100)),
                ('icon', models.CharField(help_text="Lucide icon name, e.g., 'package'", max_length=50)),
                ('agent', models.CharField(choices=[('inventory', 'Inventory'), ('broadcast', 'Broadcast'), ('finance', 'Finance'), ('hr', 'HR')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('command_template', models.CharField(help_text="Command template, e.g., 'Check stock for {item_name}'", max_length=200)),
                ('required_params', models.JSONField(default=list, help_text='List of required params, e.g., [{"name": "item_name", "label": "Item Name", "type": "text"}]')),
                ('api_endpoint', models.CharField(blank=True, max_length=200)),
                ('api_method', models.CharField(default='GET', max_length=10)),
                ('allowed_roles', models.JSONField(default=list, help_text='List of roles, e.g., ["Admin", "Teacher"]')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Quick Action',
                'verbose_name_plural': 'Quick Actions',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_input', models.TextField(help_text='Original user input')),
                ('parsed_intent', models.CharField(blank=True, max_length=100)),
                ('parsed_entities', models.JSONField(default=dict)),
                ('agent', models.CharField(choices=[('inventory', 'Inventory'), ('broadcast', 'Broadcast'), ('finance', 'Finance'), ('hr', 'HR'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('clarification_type', models.CharField(blank=True, max_length=50)),
                ('clarification_options', models.JSONField(default=list)),
                ('selected_option', models.JSONField(blank=True, null=True)),
                ('source_page', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('awaiting_clarification', 'Awaiting Clarification'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=30)),
                ('api_endpoint', models.CharField(blank=True, max_length=200)),
                ('api_method', models.CharField(blank=True, max_length=10)),
                ('api_params', models.JSONField(default=dict)),
                ('response_message', models.TextField(blank=True)),
                ('response_data', models.JSONField(default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('executed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executed_commands', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.school')),
            ],
            options={
                'verbose_name': 'Command',
                'verbose_name_plural': 'Commands',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['executed_by', '-created_at'], name='commands_co_execute_120aac_idx'), models.Index(fields=['agent', 'status'], name='commands_co_agent_76332e_idx'), models.Index(fields=['status', '-created_at'], name='commands_co_status_c8ad6c_idx')],
            },
        ),
        migrations.CreateModel(
            name='StaffAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('half_day', 'Half Day'), ('late', 'Late'), ('on_leave', 'On Leave')], max_length=20)),
                ('check_in_time', models.TimeField(blank=True, null=True)),
                ('check_out_time', models.TimeField(blank=True, null=True)),
                ('substitute_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marked_by', models.ForeignKey(help_text='Who marked this attendance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_staff_attendances', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_attendances', to='students.school')),
                ('staff', models.ForeignKey(limit_choices_to={'role__in': ['Teacher', 'Admin']}, on_delete=django.db.models.deletion.CASCADE, related_name='staff_attendances', to=settings.AUTH_USER_MODEL)),
                ('substitute', models.ForeignKey(blank=True, help_text='Substitute teacher assigned for this absence', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substitute_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Attendance',
                'verbose_name_plural': 'Staff Attendances',
                'ordering': ['-date', 'staff__first_name'],
                'indexes': [models.Index(fields=['date', 'status'], name='commands_st_date_0429db_idx'), models.Index(fields=['school', 'date'], name='commands_st_school__37d751_idx')],
                'unique_together': {('staff', 'date')},
            },
        ),
    ]
