# Generated by Django 5.2.8 on 2026-01-15 07:31

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_teacherprofile_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalarySlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(help_text='Salary period start date')),
                ('till_date', models.DateField(help_text='Salary period end date')),
                ('payment_date', models.DateField(help_text='Date of payment')),
                ('company_name', models.CharField(default='EARLY BIRD KODER KIDS PVT LTD', max_length=200)),
                ('employee_name', models.CharField(max_length=200)),
                ('employee_id_snapshot', models.CharField(blank=True, max_length=20, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('schools', models.TextField(blank=True, help_text='Schools assigned (one per line)', null=True)),
                ('date_of_joining', models.DateField(blank=True, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('no_of_days', models.IntegerField(default=0, help_text='Actual days in period')),
                ('normalized_days', models.IntegerField(default=30, help_text='Normalized days (30-day month)')),
                ('prorated_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('net_pay', models.DecimalField(decimal_places=2, default=0.0, help_text='Final amount after earnings and deductions', max_digits=10)),
                ('earnings_snapshot', models.JSONField(blank=True, default=list, help_text='JSON array of earnings at time of generation')),
                ('deductions_snapshot', models.JSONField(blank=True, default=list, help_text='JSON array of deductions at time of generation')),
                ('line_spacing', models.CharField(choices=[('single', 'Single'), ('1.5', '1.5'), ('double', 'Double')], default='1.5', max_length=10)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_by', models.ForeignKey(blank=True, help_text='Admin who generated this slip', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_salary_slips', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(help_text='Employee for whom this salary slip was generated', on_delete=django.db.models.deletion.CASCADE, related_name='salary_slips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Salary Slip',
                'verbose_name_plural': 'Salary Slips',
                'ordering': ['-generated_at'],
                'unique_together': {('teacher', 'from_date', 'till_date')},
            },
        ),
    ]
