# Generated by Django 5.2.8 on 2026-01-29 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_salaryslip'),
        ('students', '0027_guardian_review_and_school_timing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BDMVisitProforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField()),
                ('month', models.IntegerField(help_text='Month (1-12)')),
                ('year', models.IntegerField()),
                ('discipline_rating', models.IntegerField(default=3, help_text='Discipline & punctuality (1-5)')),
                ('communication_rating', models.IntegerField(default=3, help_text='Communication skills (1-5)')),
                ('child_handling_rating', models.IntegerField(default=3, help_text='Child handling & patience (1-5)')),
                ('professionalism_rating', models.IntegerField(default=3, help_text='Professionalism & dress code (1-5)')),
                ('content_knowledge_rating', models.IntegerField(default=3, help_text='Subject content knowledge (1-5)')),
                ('overall_attitude_score', models.DecimalField(decimal_places=2, default=0, help_text='Calculated from average of all ratings (0-100)', max_digits=5)),
                ('remarks', models.TextField(blank=True)),
                ('areas_of_improvement', models.TextField(blank=True)),
                ('teacher_strengths', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'BDM Visit Proforma',
                'verbose_name_plural': 'BDM Visit Proformas',
                'ordering': ['-visit_date'],
            },
        ),
        migrations.CreateModel(
            name='TeacherEvaluationScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(help_text='Month (1-12)')),
                ('year', models.IntegerField()),
                ('attendance_score', models.DecimalField(decimal_places=2, default=0, help_text='Score from TeacherAttendance (0-100)', max_digits=5)),
                ('attitude_score', models.DecimalField(decimal_places=2, default=0, help_text='Score from BDMVisitProforma (0-100)', max_digits=5)),
                ('student_interest_score', models.DecimalField(decimal_places=2, default=0, help_text='Score from TopicProgress completion rates (0-100)', max_digits=5)),
                ('enrollment_impact_score', models.DecimalField(decimal_places=2, default=0, help_text='Score from new student admissions (0-100)', max_digits=5)),
                ('total_score', models.DecimalField(decimal_places=2, default=0, help_text='Weighted total score', max_digits=5)),
                ('rating', models.CharField(choices=[('master_trainer', 'Master Trainer'), ('certified_trainer', 'Certified Trainer'), ('needs_improvement', 'Needs Improvement'), ('performance_review', 'Performance Review')], default='needs_improvement', max_length=30)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Teacher Evaluation Score',
                'verbose_name_plural': 'Teacher Evaluation Scores',
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='account_title',
            field=models.CharField(blank=True, help_text='Bank account holder name', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='account_title',
            field=models.CharField(blank=True, help_text='Bank account holder name', max_length=150, null=True),
        ),
        migrations.AddIndex(
            model_name='salaryslip',
            index=models.Index(fields=['teacher'], name='employees_s_teacher_5e8d2f_idx'),
        ),
        migrations.AddIndex(
            model_name='salaryslip',
            index=models.Index(fields=['from_date', 'till_date'], name='employees_s_from_da_d5d105_idx'),
        ),
        migrations.AddIndex(
            model_name='salaryslip',
            index=models.Index(fields=['generated_at'], name='employees_s_generat_dd39d6_idx'),
        ),
        migrations.AddField(
            model_name='bdmvisitproforma',
            name='bdm',
            field=models.ForeignKey(help_text='BDM who filled this proforma', limit_choices_to={'role': 'BDM'}, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_proformas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bdmvisitproforma',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bdm_proformas', to='students.school'),
        ),
        migrations.AddField(
            model_name='bdmvisitproforma',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'role': 'Teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='bdm_proformas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teacherevaluationscore',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'role': 'Teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_scores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='bdmvisitproforma',
            unique_together={('teacher', 'school', 'month', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='teacherevaluationscore',
            unique_together={('teacher', 'month', 'year')},
        ),
    ]
