# Generated by Django 5.1.15 on 2026-03-01 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_create_bdm_profiles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_lead_assignment', models.BooleanField(default=True, help_text='Lead Assignment Email -> BDM')),
                ('email_lead_reassignment', models.BooleanField(default=True, help_text='Lead Reassignment Email -> New BDM')),
                ('email_bulk_lead_assignment', models.BooleanField(default=True, help_text='Bulk Lead Assignment Email -> Each BDM')),
                ('email_activity_scheduled', models.BooleanField(default=True, help_text='Activity Scheduled Email -> Assigned BDM')),
                ('email_aging_lead_alert', models.BooleanField(default=True, help_text='Aging Lead Alert Email -> BDMs (daily 9 AM)')),
                ('email_task_assignment', models.BooleanField(default=True, help_text='Task Assignment Email -> Assignee')),
                ('email_bulk_task_assignment', models.BooleanField(default=True, help_text='Bulk Task Assignment Email -> Each assignee')),
                ('email_welcome', models.BooleanField(default=True, help_text='Welcome Email -> New user')),
                ('email_password_reset', models.BooleanField(default=True, help_text='Password Reset Email -> User')),
                ('email_school_assignment', models.BooleanField(default=True, help_text='School Assignment Email -> Teacher')),
                ('email_account_update', models.BooleanField(default=True, help_text='Account Update Email -> User')),
                ('email_student_progress', models.BooleanField(default=True, help_text='Student Progress Email -> Student')),
                ('inapp_monthly_report_reminder', models.BooleanField(default=True, help_text='Monthly Report Reminder -> All teachers (28th)')),
                ('inapp_bdm_creates_lead', models.BooleanField(default=True, help_text='BDM Creates Lead -> All admins')),
                ('inapp_bdm_updates_lead', models.BooleanField(default=True, help_text='BDM Updates Lead -> All admins')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notification Settings',
                'verbose_name_plural': 'Notification Settings',
            },
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role__in': ['Teacher', 'Admin', 'BDM']}, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
