# Generated by Django 5.2.11 on 2026-09-11 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_salarychangelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryslip',
            name='absent_days',
            field=models.IntegerField(default=0, help_text='Working days marked absent'),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='present_days',
            field=models.IntegerField(default=0, help_text='Working days marked present'),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='total_working_days',
            field=models.IntegerField(default=0, help_text="Total working days in the period, from assigned schools' class days"),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='working_days_snapshot',
            field=models.JSONField(blank=True, default=list, help_text='JSON array of {date, weekday, status} for each working day in the period'),
        ),
    ]
